### ISSUE TITLE
"ERROR: invalid redefinition of constant" when package name matches a message name.

### ISSUE THREAD

**Issue by sbchisholm** [tanmaykm/ProtoBuf.jl#36]
protobuf [Foo.proto]:
```protobuf
package PB.Foo;

message Foo {
  required string bar = 1;
}
```

julia [PB.jl]:
```julia
module PB
  module Foo
    include("Foo_pb.jl")
  end
end
```

julia [Foo_pb.jl]:
```julia
using ProtoBuf
import ProtoBuf.meta

type Foo
    bar::String
    Foo() = (o=new(); fillunset(o); o)
end #type Foo
const __req_Foo = Symbol[:bar]
meta(t::Type{Foo}) = meta(t, __req_Foo, ProtoBuf.DEF_FNUM, ProtoBuf.DEF_VAL, true, ProtoBuf.DEF_PACK, ProtoBuf.DEF_WTYPES)

export Foo
```

When trying `using PB` the result is "ERROR: invalid redefinition of constant".

**Comment by sbchisholm** [comment]
The problem is that the line `package PB.Foo` generates a `module Foo` and the line `message Foo {` generates a `type Foo`, resulting the redefinition error.

**Comment by sbchisholm** [comment]
The ProtoBuf works fine in code generated for C++ or Python, it would be nice if this could also work with Julia.

**Comment by tanmaykm** [comment]
Oops. But I feel generating packages as modules is a better approach. The previous mechanism was resulting in not so nice type names that were prefixed with package names. 

But looks like we need to fall back to that in this case (and I think this is the only such case).

**Comment by sbchisholm** [comment]
@tanmaykm, What are you thoughts on added a postfix on the module name so in this case we'd generate PB.jl as:

```julia
module PB
  module Foo_pb
    include("Foo_pb.jl")
  end
end
```

**Comment by tanmaykm** [comment]
It will still break if:
````
package PB.Foo;

message Foo_pb {
  required string bar = 1;
}
````

This is also similar to handling name clashes with Julia keywords. It's currently handled at https://github.com/tanmaykm/ProtoBuf.jl/blob/master/src/gen.jl#L82, which is not very robust.

**Comment by tanmaykm** [comment]
How about maintaining a per module symbol list during code generation and a set of disambiguation rules.

**Comment by sbchisholm** [comment]
What do you have in mind for the disambiguation rules?
