### ISSUE TITLE
Nested types do not defer in in package

### ISSUE THREAD

**Issue by wildart** [tanmaykm/ProtoBuf.jl#42]
If a package is declared then some of types with nested types are not deferred till nested types are being resolved. This results in parent types are being listed before children types. Here is an example:
```proto
package P;
message A {
  required string a = 1;
  message B {
    optional C c = 1;
  }
  optional B b = 2;
}
message C {
  required string c = 1;
}
```
Above example will generate a code where type `A` will be listed before `A_B`, resulting in a compilation error.  If `package` is commented then the code is properly generated, `A_B` before `A`.

**Comment by tanmaykm** [comment]
Should be fixed by #43.
Thanks for reporting!
