### ISSUE TITLE
Int32 vs. int32, etc

### ISSUE THREAD

**Issue by waTeim** [tanmaykm/ProtoBuf.jl#48]
Hey I'm just beginning to use this so perhaps is a simple fix or not even an error.  I suspect typenames changing from julia 0.3.x to Julia 0.4.x is to blame.  I've injected a print statement just prior to the error, I think it illustrates the problem.

    julia> include("generated/caffe.jl")
    caffe

    julia> f = open("bvlc_googlenet.caffemodel")
    IOStream(<file bvlc_googlenet.caffemodel>)

    julia> x = ProtoBuf.readproto(f,caffe.BlobProto())
    (0,:write_varint,:read_varint,Int32) 
    ERROR: cannot read wire type 2 as int32       <---- because int32 != Int32?
     in error at /usr/local/julia-ab4f68468a/lib/julia/sys.dylib
     in readproto at /Users/jeffw/.julia/v0.4/ProtoBuf/src/codec.jl:345
     in readproto at /Users/jeffw/.julia/v0.4/ProtoBuf/src/codec.jl:308

**Comment by tanmaykm** [comment]
Doesn't seem like. Wire type 2 indicates a length delimited field (https://github.com/tanmaykm/ProtoBuf.jl/blob/3d335bb6820e1b0a46517dcff52b2525f15ba14f/src/codec.jl#L8)

This looks more like a data corruption or the data is not really the same as `caffe.BlobProto`.
It will probably help if you can narrow it down to a smaller independent piece of code.

**Comment by waTeim** [comment]
I  think you are right and it's not a BlobProto though I'm not sure what it is if not that.  Maybe the [prototext](https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet) defines the messages?  Here's [a reference](http://caffe.berkeleyvision.org/tutorial/net_layer_blob.html) to the caffe organization.  I'm 100% sure it's not a corrupted file.

**Comment by tanmaykm** [comment]
It's probably a serialized form of the network as described here: http://arxiv.org/abs/1409.4842

Can you try reading it as `caffe.NetParameter()` instead?

**Comment by waTeim** [comment]
Oh yes that worked, I think ... perfectly here's [some output](https://gist.github.com/waTeim/e6936f93ab2e26d136c1)

**Comment by tanmaykm** [comment]
:thumbsup:
