### ISSUE TITLE
Question: Deserializing Python Protobuf object

### ISSUE THREAD

**Issue by xanderdunn** [tanmaykm/ProtoBuf.jl#54]
I'm using Protobuf between Python and Julia.  

To get a Protobuf object Julia -> Python, I write it to a `PipeBuffer`, which appears on the Python side as `buffer` object `<type 'PyCall.jl_IO'>` using PyCall.jl.  Then I can instantiate the object from the Protobuf bytes like this `myObject.ParseFromString(bytes(buffer.read()))`.  All good.  

Now, I'm having trouble going in the opposite direction: Python -> Julia.  In Python, I encode an object as Protobuf and store it as a byte array: 
```python
array = bytearray()
array.extend(proto_action.SerializeToString())
```

In Julia this is an `Array{UInt8, 1}`, which I read into a `PipeBuffer`, but then I'm unable to deserialize it: 
```julia
iob = PipeBuffer()
write(iob, x)
deserialized = readproto(iob, ProtobufTypes.Action())
```

Produces error `ERROR: LoadError: cannot read wire type 2 as int32`.  I suspect I'm simply misrepresenting the object at some step.

**Comment by tanmaykm** [comment]
@xanderdunn can you post some code to replicate this? 

Is it possible that the received buffer is somehow corrupted by the string encoding resulting from `proto_action.SerializeToString()`?

**Comment by tanmaykm** [comment]
Assuming solution found. Closing.
@xanderdunn please reopen if still an issue.
