### ISSUE TITLE
support protobuf3?

### ISSUE THREAD

**Issue by ekg** [tanmaykm/ProtoBuf.jl#55]
As far as I understand, protobuf3 is even simpler to implement, particularly given changes in default value semantics. Have you thought about supporting it?

**Comment by tanmaykm** [comment]
Yes of course. There was at least one discussion mentioning this here: https://github.com/tanmaykm/ProtoBuf.jl/issues/46#issuecomment-104119782

Right now, ver 2 seems sufficient for most cases that I have encountered. I shall probably attempt it when I do any changes to the package next. Please feel free to send in a PR if you need it in the meantime.

**Comment by malmaud** [comment]
One place where protobuf3 would be useful is for supporting [Tensorflow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/graph.proto).

**Comment by tanmaykm** [comment]
I had attempted this some time ago. Should be able to push an update this week.

**Comment by tanmaykm** [comment]
FWIW, I'm working further on it, but there's basic support for protobuf3 now in this branch: https://github.com/tanmaykm/ProtoBuf.jl/tree/proto3.

**Comment by malmaud** [comment]
Oh great, thank you so much.

**Comment by tanmaykm** [comment]
Protobuf3 support should now be available in master via #70.
Do raise issues if something is not working fine.
Will tag a new version soon.
