### ISSUE TITLE
ability to handle packed fields (patch suggestion)

### ISSUE THREAD

**Issue by hrobotron** [tanmaykm/ProtoBuf.jl#64]
Hello, 1st of all, thanks for the great ProtoBuf.jl package, helping a lot with my scientific experiments.

As described in Q&A in https://groups.google.com/forum/#!topic/protobuf/RtAhGr4EPzQ the reading side of protobuf is supposed to accept packed format of repeated fields, no matter whether declared so in .proto. In current version it fails. I am attaching simplified test setup, reading an array of 1 double value, non-packed and packed input data.

I think the working solutin shall be to replace codec.jl@l.335 `if attrib.packed`by `if wiretyp == WIRETYP_LENDELIM`. I can not imagine whether it may break another stuff, but seems to me to be OK.

Best regards, Marek
[julia_pb_packed.tar.gz](https://github.com/tanmaykm/ProtoBuf.jl/files/335946/julia_pb_packed.tar.gz)

**Comment by tanmaykm** [comment]
Thanks @hrobotron, your analysis does look correct.
I shall test it and confirm.

**Comment by hrobotron** [comment]
Excellent, many thanks for your quick action!
