### ISSUE TITLE
writing to websockets?

### ISSUE THREAD

**Issue by zahachtah** [tanmaykm/ProtoBuf.jl#67]
I have very little experience with websockets and protobuff but I have got a web socket implementation working (showing a scientific simulation in realtime). I am not very skilled at programming and I can't figure out how to write the protobuf to the web socket. 

in websockets.jl examples the relevant line is:

write(client,msg)

it seems I cannot change that to protowrite(client,myType).

any advice how to do this would be much appreciated. 

sorry if this is obvious :-/

**Comment by tanmaykm** [comment]
The API is `writeproto` and it accepts `IO` as the first parameter.
This should work: `writeproto(client, msg)`.

Let me know if this is still an issue.

**Comment by zahachtah** [comment]
My dumb, I had used writeproto(client, msg) as you suggested, but had brain misfire when I wrote the issue. 

But I figured it out, Client.socket holds the actual IO so

writeproto(client.socket, msg)

works!
