### ISSUE TITLE
You can not store noncustom types?

### ISSUE THREAD

**Issue by oxinabox** [tanmaykm/ProtoBuf.jl#73]
Writing a plain Vector{Float64} does not work.

```
In>
xx = randn(5)
@show xx
iob = PipeBuffer();
writeproto(iob, xx);   # write an instance of it
@show length(iob.data) #Look No data is written
@show readproto(iob, zeros(xx))

Out>
xx = [0.267308,-1.96712,1.2049,0.0836903,-0.340703]
length(iob.data) = 0
readproto(iob,zeros(xx)) = [0.0,0.0,0.0,0.0,0.0]

```

but putting it into a custom type works fine:

```
IN>
type Foo
    v::Vector{Float64}
    Foo() = new()
    Foo(v1) = new(v1)
end

xx = randn(5)
@show xx
iob = PipeBuffer();
writeproto(iob, Foo(xx));   # write an instance of it
@show length(iob.data) #Look data was written
@show readproto(iob, Foo())

OUT>
xx = [1.2503,0.613713,-1.18542,1.25501,0.803276]
length(iob.data) = 45
readproto(iob,Foo()) = Foo([1.2503,0.613713,-1.18542,1.25501,0.803276])
```

Is this a feature/part of the spec?
I kinda would expect some kind of exception or warning if nothing is written to the buffer.
And something in the docs saying you can't do this -- if this is a feature.

**Comment by tanmaykm** [comment]
Yes, that's expected.
ProtoBuf can serialize `messages`, which map on to Julia composite types.

**Comment by tanmaykm** [comment]
In the master branch there's `writeproto{T}(io::IO, val::Array{T}, attrib::ProtoMetaAttribs)`. You need to pass an appropriate instance of `ProtoMetaAttribs`.

There's no corresponding `readproto` though. And it will be incompatible with ProtoBuf libraries for other languages.

**Comment by oxinabox** [comment]
Should anytime you call `writeproto`, that results in zero bytes being written, raise an exception, or a warning perhaps?

**Comment by tanmaykm** [comment]
I don't think so. Because there could be instances where no bytes are serialized. E.g.:
- serializing with only default values
- https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty
