### ISSUE TITLE
Having `google` module is problematic

### ISSUE THREAD

**Issue by malmaud** [tanmaykm/ProtoBuf.jl#77]
So it turns out that if you made a module that has a `using ProtoBuf`, and then try to precompile your module, you'll get an error that the module `google` cannot be found. This is because precompilation doesn't like that ProtoBuf.jl defines both `ProtoBuf` and `google` in global scope - can we refactor things so that `google` is a submodule of `ProtoBuf` to fix this?

**Comment by tanmaykm** [comment]
Ah! Didn't realize that would be a problem with precompilation.
It should be possible to make `google` a submodule. Will take a look.

**Comment by tanmaykm** [comment]
I recollect the reason for not making this a submodule now:

Extensions are just regular protobuf namespaces in the protobuf specification. Generating them as a submodule may require us to have special treatment for them in the code generator.

**Comment by tanmaykm** [comment]
@malmaud Could you try out with the changes in the `proto3` branch (PR: #78)

**Comment by malmaud** [comment]
Yep, that works great.

**Comment by malmaud** [comment]
Great! Can we tag a release?

**Comment by tanmaykm** [comment]
PR already at: https://github.com/JuliaLang/METADATA.jl/pull/6646
