### ISSUE TITLE
-1 turns into 0 when parsing a packed int32 field

### ISSUE THREAD

**Issue by malmaud** [tanmaykm/ProtoBuf.jl#86]
I created a Python and a Julia protobuf parser from https://gist.github.com/malmaud/41e922caed12cce92a3ce3fdfb3b9eb5#file-hi-proto, generating https://gist.github.com/malmaud/41e922caed12cce92a3ce3fdfb3b9eb5#file-hi_pb2-py and https://gist.github.com/malmaud/41e922caed12cce92a3ce3fdfb3b9eb5#file-hi_pb-jl respectively. 

I created a serialized protobuffer from Python as

```python
import hi_pb2
hi = hi_pb2.Hi()
hi.x.append(-1)
f = open("test.pb", "w")
f.write(hi.SerializeToString())
```

That file is at https://www.dropbox.com/s/sggmctao6t0bea7/test.pb?dl=1, and parses correctly if you reload it in Python with `ParseFromString`. 

In Julia, I then did

```julia
using ProtoBuf
include("hi_pb.jl")
b = IOBuffer(read("test.pb"))
seekstart(b)
hi = Hi()
readproto(b, Hi)
```

producing `Hi(Int32[0])`, instead of the expected `Hi(Int32[-1])`.

**Comment by malmaud** [comment]
Actually, it doesn't matter if it's packed or not: All `uint32` negative field values turn into zero.

**Comment by tanmaykm** [comment]
looking at it now..

**Comment by tanmaykm** [comment]
Strangely, it looks like both negative `int32` and `int64` should encode to 10 bytes.

from https://developers.google.com/protocol-buffers/docs/encoding:
> if you use int32 or int64 as the type for a negative number, the resulting varint is always ten bytes long – it is, effectively, treated like a very large unsigned integer.
